// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.3
// source: proto/image.proto

package rpc_protocol

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ImageClassifyClient is the client API for ImageClassify service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ImageClassifyClient interface {
	ClassifyImage(ctx context.Context, in *ImageClassifierRequest, opts ...grpc.CallOption) (*ImageClassifierReply, error)
}

type imageClassifyClient struct {
	cc grpc.ClientConnInterface
}

func NewImageClassifyClient(cc grpc.ClientConnInterface) ImageClassifyClient {
	return &imageClassifyClient{cc}
}

func (c *imageClassifyClient) ClassifyImage(ctx context.Context, in *ImageClassifierRequest, opts ...grpc.CallOption) (*ImageClassifierReply, error) {
	out := new(ImageClassifierReply)
	err := c.cc.Invoke(ctx, "/image.ImageClassify/ClassifyImage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ImageClassifyServer is the server API for ImageClassify service.
// All implementations must embed UnimplementedImageClassifyServer
// for forward compatibility
type ImageClassifyServer interface {
	ClassifyImage(context.Context, *ImageClassifierRequest) (*ImageClassifierReply, error)
	mustEmbedUnimplementedImageClassifyServer()
}

// UnimplementedImageClassifyServer must be embedded to have forward compatible implementations.
type UnimplementedImageClassifyServer struct {
}

func (UnimplementedImageClassifyServer) ClassifyImage(context.Context, *ImageClassifierRequest) (*ImageClassifierReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClassifyImage not implemented")
}
func (UnimplementedImageClassifyServer) mustEmbedUnimplementedImageClassifyServer() {}

// UnsafeImageClassifyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImageClassifyServer will
// result in compilation errors.
type UnsafeImageClassifyServer interface {
	mustEmbedUnimplementedImageClassifyServer()
}

func RegisterImageClassifyServer(s grpc.ServiceRegistrar, srv ImageClassifyServer) {
	s.RegisterService(&ImageClassify_ServiceDesc, srv)
}

func _ImageClassify_ClassifyImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImageClassifierRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageClassifyServer).ClassifyImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/image.ImageClassify/ClassifyImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageClassifyServer).ClassifyImage(ctx, req.(*ImageClassifierRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ImageClassify_ServiceDesc is the grpc.ServiceDesc for ImageClassify service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ImageClassify_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "image.ImageClassify",
	HandlerType: (*ImageClassifyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ClassifyImage",
			Handler:    _ImageClassify_ClassifyImage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/image.proto",
}
