FROM alpine:latest

LABEL author="devhoodit"

RUN apk update && apk upgrade && apk add --no-cache rc-service

WORKDIR /server


COPY build/was-linux-amd64 .
COPY /templates ./templates
COPY /static ./static 
COPY example.yaml config.yaml

ENV GIN_MODE=release

EXPOSE 443

ENTRYPOINT ["./was-linux-amd64"]