service:
  address: ":8080"
  cors:
    allowOrigins:
      - "*"
    allowMethods:
      - GET
      - DELETE
      - PUT
      - POST
    allowHeaders:
    allowCredentials: true
    exposeHeaders:

    maxAge: 3600 # seconds
    allowWildcard: false
    allowBrowserExtensions: false
    allowWebSockets: true
    allowFiles: false # warning, false is default
  log:
    path: ./logs/app.log
    maxSize: 10
    maxBackups: 3
    maxAge: 30
    console: true

mysql:
  username: root
  password: password
  address: localhost
  port: 3306

redis:
  address: localhost:6379
  password: ""
  db: 0

key:
  jwtkey: jwtkey
  sessionStateKey: sessionStateKey

oauth:
  github:
    id: "client id"
    secret: "client secret"
    redirect: "redirect url"

email:
  mock:
    type: "default"

storage:
  local:
    baseDirectory: "base directory path"

  s3:
    region: "region"
    bucketName: "name"
    id: "id" # optional
    key: "key" # optional
